apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod-dns
  name: what-is-my-ipv6-gateway
  namespace: what-is-my-ipv6
spec:
  gatewayClassName: eg
  infrastructure:
    annotations:
      metallb.io/ip-allocated-from-pool: ipv6-default
  listeners:
  - allowedRoutes:
      namespaces:
        from: All
    name: http
    port: 80
    protocol: HTTP
  - allowedRoutes:
      namespaces:
        from: All
    hostname: ipv6.br0.no
    name: https
    port: 443
    protocol: HTTPS
    tls:
      certificateRefs:
      - group: ""
        kind: Secret
        name: what-is-my-ipv6-gateway
      mode: Terminate