apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  annotations:
    external-dns.alpha.kubernetes.io/hostname: https.br0.no
  name: what-is-my-ipv6-httproute
  namespace: what-is-my-ipv6
spec:
  hostnames:
  - ipv6.br0.no
  parentRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: what-is-my-ipv6-gateway
    namespace: what-is-my-ipv6
  rules:
  - backendRefs:
    - group: ""
      kind: Service
      name: what-is-my-ipv6
      port: 80
      weight: 1
    matches:
    - path:
        type: PathPrefix
        value: /
